 

FROM envoyproxy/envoy:v1.12.2 as builder

FROM ubuntu:22.04

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y ca-certificates \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/envoy

COPY --from=builder /usr/local/bin/envoy /usr/local/bin/envoy
COPY --from=builder /etc/envoy/envoy.yaml /etc/envoy/envoy.yaml

 

# ADD build_release_stripped/envoy /usr/local/bin/envoy
# ADD configs/google_com_proxy.v2.yaml /etc/envoy/envoy.yaml

EXPOSE 10000

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["envoy", "-c", "/etc/envoy/envoy.yaml"]
